### ISSUE TITLE
kanband Board Setup

### ISSUE THREAD

**Issue by Profsain** [Profsain/rails_recipe_app#13]
Hi reviewer, In this project, we are 3 members in the group, and all task is distributed equally among each member.
Project Link: https://github.com/users/Profsain/projects/6/views/1

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  🏃 🏃‍♂️ 🏃‍♀️  

## Highlights 👍  
- Good job so far with tasks distribution!

## Required Changes ♻️
- [ ] Task description are missing from the cards. Please ensure **all** cards have description provided.
**Missing Task descriptions:**
![image](https://user-images.githubusercontent.com/12745474/218529254-27f10ff2-c5df-4740-88ae-db5817862815.png)
- [ ] Let's ensure that tasks are distributed in a fair way by assigning task points to each task, as can be seen in the below screenshot. Please ensure that each student does not have more or less than 5 points.
**Points assigning:**
![image](https://user-images.githubusercontent.com/12745474/218530924-ebb44cbc-7b67-4322-9f32-12952c79b80d.png)

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
